### ISSUE TITLE
webserver invalid port specification

### ISSUE THREAD

**Issue by depaolim** [painless-software/painless-continuous-delivery#10]
After the initialization of the project i run:
`docker-compose up --build -d`
and I got:
```
ERROR: for webserver  Cannot create container for service webserver: b'invalid port specification: "None"'
ERROR: compose.cli.main.main: Encountered errors while bringing up the project.
```

**Comment by depaolim** [comment]
I'm not sure this is the right solution, I made a pull request just to make a proposal and discuss it. Thanks

**Comment by depaolim** [comment]
Ok, obviously this is not the solution: removing "ports" makes nginx un-accessible from the host!
But I still can't figure up how to solve my problem...

**Comment by depaolim** [comment]
ok! Solved it was docker-compose install issue!

Follow this instructions:
https://github.com/docker/compose/releases

**Comment by bittner** [comment]
Thanks for sharing your issues. And sorry that nobody jumped in immediately to point you in the right direction. (PyCon kept us busy last week, I guess.)

The Docker setup will see some improvement in the next couple of weeks. You may want to revisit the project later this or next month, and give the setup another try.

**Comment by depaolim** [comment]
Sure! And thanks for this usefull repo!
