### ISSUE TITLE
Syntax "only" on GitLab CI deprecation

### ISSUE THREAD

**Issue by DimasInchidi** [painless-software/painless-continuous-delivery#125]
In favor of `rules` syntax on Gitlab CI configuration, `only` will be deprecated on 22nd May 2020.
read more here: https://about.gitlab.com/releases/2020/05/06/gitlab-com-13-0-breaking-changes/#auto-devops-and-secure-configuration-templates-are-changing-to-rules-instead-of-onlyexcept

this project using `only` in all `painless-continuous-delivery/{{cookiecutter.project_slug}}/_/ci-services/*/.gitlab-ci.yml`

**Comment by bittner** [comment]
Thanks for letting us know! We're aware of this change and will take the necessary steps in due time.

**Comment by bittner** [comment]
In a discussion on the GitLab issue tracker it was clarified that `only`/`except` will not be removed. It has shown that the verbose nature of `rules` causes other issues, confusing side-effects among others.

Unless there is a good reason for switching it hence makes sense to stick with `only`/`except`.

## References

- https://docs.gitlab.com/ee/ci/yaml/#only--except
- https://twitter.com/j4yav/status/1260548837023850496
