### ISSUE TITLE
A valid repository [...] could not be found in the following locations

### ISSUE THREAD

**Issue by cool-RR** [painless-software/painless-continuous-delivery#40]
I ran this on Windows 7:

    $ cookiecutter.exe gh:cool-RR/PySnooper
    Username for 'https://github.com': cool-RR
    Password for 'https://cool-RR@github.com':
    A valid repository for "https://github.com/cool-RR/PySnooper.git" could not be found in the following
     locations:
    c:\Users\Administrator\.cookiecutters\PySnooper

Note that a repo was indeed created in `c:\Users\Administrator\.cookiecutters\PySnooper`

**Comment by cool-RR** [comment]
I believe this is happening because you're using the https remote instead of the git@github.com remote. Maybe the fact it's a private repo is related.

**Comment by bittner** [comment]
I believe you're misinterpreting [the instructions of the README](https://github.com/painless-software/painless-continuous-delivery#usage): You should run the cookiecutter command with this cookiecutter, i.e.
```
$ cookiecutter gh:painless-software/painless-continuous-delivery
```
This should then start an interactive session asking you a few question to customize the generated project skeleton.

Does this help?

**Comment by cool-RR** [comment]
Ah, you're right. Thanks.
