### ISSUE TITLE
Old Tags do not get cleaned up on Gitlab.com

### ISSUE THREAD

**Issue by ccremer** [painless-software/painless-continuous-delivery#65]
Even though the repository on Gitlab.com is cleaned every day, it does not delete old tags: https://gitlab.com/appuio/example-django/-/tags

Currently there is: 
* 1.0.0 (Jan 15, 7:54), made by Bot
* 1.1.0 (Jan 13, 4:55), made by me

Logically the tag 1.1.0 shouldn't exist before 1.0.0 :)

**Comment by bittner** [comment]
That makes sense. We should clean up the tags before deploying an update of the demo. The change needs to be done [in the field test script](https://github.com/painless-software/painless-continuous-delivery/blob/master/tests/field/example-django.sh#L29-L33).

Note that currently only MRs are cleaned up, no branches are delete either. We may want to consider cleaning that up, too. Although, this can come in handy sometimes ("what was it that I tried out as a MR yesterday", the feature branch is still around) and is also no big deal to delete manually from time to time.

**Comment by ccremer** [comment]
While I understand your argumentation, for me it's difficult to know which is being deleted and which stuff is being kept. In my understanding I assumed that this demo should be treated as ephemeral that gets reset completely ("everything") every night, so we have a clean plate for demonstrations without yesterday's stuff. Maybe the actual development on the example should be done in a different Repo?
